### ISSUE TITLE
Can't install this extension using Brave browser

### ISSUE THREAD

**Issue by kkorus** [orschiro/Alt-Q-Switch-Tabs-Keyboard-Shortcut#38]
Hi, there is an issue with Chromium base browser Brave. When click it to install it says "Installing" and I developers console there are logline:
`Unchecked runtime.lastError: Access denied.`

**Comment by orschiro** [comment]
@kkorus thanks for reporting. This is an upstream issue. Can you please report here?

https://github.com/brave/brave-browser
